#!/usr/bin/python
#-*- coding:utf-8 -*-
import random   #加载随机模块

print("this is a python program\n")
print("now i have a numbers\n")
print("this is an integer from 0 to 10\n")

num=random.randint(0,10)
guess=input("Guess it:")
guess=int(guess)
t=3
while  t!=1:
    t-=1
    if guess==num :
        print("\nYes!You are right:",num,'\n')
        break
    elif guess>num:
        print("\n====>Bigger<====\n")
        guess=int(input("Please try again:"))        
        continue
    elif guess<num:
        print("\n====>Smaller<====\n")
        guess=int(input("Please try again:"))
        continue
else:
    print("\nSorry! your time has been run out of\n")
